const express = require('express');
const router = express.Router();
const { validateChatRequest } = require('../src/validation');
const { sanitizeMessage } = require('../src/sanitizer');
const { generateReply, generateAnswer, buildFullPrompt } = require('../src/answering');
const { streamAnswer, hasLLM } = require('../src/llm');
const { webSearch } = require('../src/websearch');
const { generateImage, detectImageRequest } = require('../src/imagegen');
const { matchAndExecute } = require('../src/plugins');
const { buildMemoryPrompt } = require('../src/memory');
const db = require('../src/db');
const logger = require('../src/logger');

router.post('/', async (req, res) => {
  const startTime = Date.now();
  try {
    const result = validateChatRequest(req.body);
    if (!result.valid) {
      logger.warn('Invalid chat request', { error: result.error });
      return res.status(400).json({ error: result.error });
    }

    const sanitized = sanitizeMessage(result.message);
    const history = Array.isArray(req.body.history) ? req.body.history.slice(-10) : [];
    const mode = result.mode || 'default';
    const image = result.image || null;
    const pdfContext = req.body.pdfContext || null;

    const reply = await generateReply(sanitized, result.personality, history, {
      mode,
      image,
      pdfContext,
    });

    const responseTime = Date.now() - startTime;
    logger.debug('Chat request completed', {
      messageLength: sanitized.length,
      personality: result.personality,
      responseTime: `${responseTime}ms`,
    });

    res.json({ reply });
  } catch (error) {
    const responseTime = Date.now() - startTime;
    logger.error('Error in /api/chat', {
      error: error.message,
      stack: error.stack,
      responseTime: `${responseTime}ms`,
    });
    res.status(500).json({
      error: 'Failed to generate response. Please try again.',
      timestamp: new Date().toISOString(),
    });
  }
});

router.post('/stream', async (req, res) => {
  try {
    const result = validateChatRequest(req.body);
    if (!result.valid) {
      return res.status(400).json({ error: result.error });
    }

    const sanitized = sanitizeMessage(result.message);
    const history = Array.isArray(req.body.history) ? req.body.history.slice(-10) : [];
    const mode = result.mode || 'default';
    const image = result.image || null;
    const pdfContext = req.body.pdfContext || null;
    const personality = result.personality;

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no',
    });

    let searchContext = null;
    if (mode === 'web-search' && hasLLM()) {
      res.write(`data: ${JSON.stringify({ thinking: 'Searching the web...' })}\n\n`);
      const results = await webSearch(sanitized, 5);
      if (results.length > 0) {
        const contextParts = results
          .map((r, i) => `[Source ${i + 1}] ${r.title}\nURL: ${r.url}\n${r.snippet}`)
          .join('\n\n');
        searchContext = `Web Search Results for "${sanitized}":\n\n${contextParts}\n\nUse this information to provide accurate, up-to-date answers.`;
        res.write(
          `data: ${JSON.stringify({ thinking: 'Found ' + results.length + ' results. Generating response...' })}\n\n`
        );
      }
    }

    const effectiveContext = searchContext || pdfContext;
    const memoryPrompt = buildMemoryPrompt(req.userId, history);
    const userLongTermMemory = db.getUserMemory(req.userId);
    let fullPersonalityPrompt = buildFullPrompt(sanitized, personality, {
      mode,
      pdfContext: !!effectiveContext,
    });
    if (memoryPrompt) {
      fullPersonalityPrompt += '\n\n' + memoryPrompt;
    }
    if (userLongTermMemory) {
      fullPersonalityPrompt += '\n\nLong-term memory about user: ' + userLongTermMemory;
    }

    if (req.body.customInstructions) {
      fullPersonalityPrompt += '\n\nAdditional user preferences: ' + req.body.customInstructions;
    }
    if (req.body.nickname) {
      fullPersonalityPrompt += "\n\nThe user's name is " + req.body.nickname + '.';
    }
    if (req.body.occupation) {
      fullPersonalityPrompt += "\n\nThe user's occupation is: " + req.body.occupation + '.';
    }

    if (mode === 'deep-research' && hasLLM()) {
      res.write(`data: ${JSON.stringify({ thinking: 'Conducting deep research...' })}\n\n`);
    }

    if (detectImageRequest(sanitized)) {
      res.write(`data: ${JSON.stringify({ thinking: 'Generating image...' })}\n\n`);
      const imageData = await generateImage(sanitized);
      if (imageData) {
        res.write(
          `data: ${JSON.stringify({ chunk: `Here is the image I generated based on your request:\n\n![Generated Image](${imageData})\n\n_Image generated by AI_` })}\n\n`
        );
      } else {
        res.write(
          `data: ${JSON.stringify({ chunk: `I'd love to generate an image for you! To enable image generation, set your **OPENAI_API_KEY** in .env (free at https://platform.openai.com/api-keys) or **LEONARDO_API_KEY** for Leonardo.ai.` })}\n\n`
        );
      }
      res.write(`data: [DONE]\n\n`);
      res.end();
      return;
    }

    const pluginResults = await matchAndExecute(sanitized, { llm: generateAnswer });
    let pluginHandled = false;
    for (const { pluginId, result: pResult } of pluginResults) {
      if (pResult && pResult.text) {
        res.write(`data: ${JSON.stringify({ chunk: `${pResult.text}` })}\n\n`);
        if (['weather', 'calculator', 'reminder'].includes(pluginId)) {
          pluginHandled = true;
        }
      }
    }

    if (pluginHandled) {
      res.write(`data: [DONE]\n\n`);
      res.end();
      return;
    }

    await streamAnswer(
      sanitized,
      effectiveContext,
      history,
      fullPersonalityPrompt,
      { mode, image, userId: req.userId },
      (chunk) => {
        res.write(`data: ${JSON.stringify({ chunk })}\n\n`);
      },
      () => {
        res.write(`data: [DONE]\n\n`);
        res.end();
      },
      (err) => {
        logger.error('Stream error', { error: err.message });
        res.write(`data: ${JSON.stringify({ error: err.message })}\n\n`);
        res.write(`data: [DONE]\n\n`);
        res.end();
      }
    );
  } catch (error) {
    logger.error('Error in /api/chat/stream', { error: error.message });
    if (!res.headersSent) {
      res.status(500).json({ error: 'Streaming failed' });
    } else {
      res.end();
    }
  }
});

module.exports = router;
